#action.yaml
name: Send email notification on failure
description: for sending failure email
author: KKumari
branding:
  icon: 'activity'
  color: 'yellow'
inputs:
  username:
    description: 'email of user'
    required: true
  password:
    description: 'password'
    required: true
  
steps:
    runs : python unsuccessful.py gitjob1 gitrepos1 gitwork1
